Table "ANIMAL" {
  "code espèce"         VARCHAR(42) [NOT NULL]
  "nom"                 VARCHAR(42) [NOT NULL]
  "date naissance"      VARCHAR(42) [NOT NULL]
  "sexe"                VARCHAR(42)
  "date décès"          VARCHAR(42)
  "code espèce mère"    VARCHAR(42) ["NULL"]
  "nom mère"            VARCHAR(42) ["NULL"]
  "date naissance mère" VARCHAR(42) ["NULL"]
  "type alimentation"   UNSIGNED_INT ["NULL"]
  "est carnivore"       BOOLEAN [NOT NULL]
  "quantité viande"     VARCHAR(42) ["NULL"]
  "est herbivore"       BOOLEAN [NOT NULL]
  "plante préférée"     VARCHAR(42) ["NULL"]
  Indexes {
    ("code espèce", "nom", "date naissance") [pk]
  }
}

Table "ESPÈCE" {
  "code espèce"      VARCHAR(42) [pk, NOT NULL]
  "nom latin"        VARCHAR(42)
  "nom vernaculaire" VARCHAR(42)
  Indexes {
    "nom latin" [unique]
  }
}

Table "OCCUPE" {
  "code espèce"    VARCHAR(42) [NOT NULL]
  "nom"            VARCHAR(42) [NOT NULL]
  "date naissance" VARCHAR(42) [NOT NULL]
  "num. enclos"    VARCHAR(42) [NOT NULL]
  "date début"     VARCHAR(42) [NOT NULL]
  "date fin"       VARCHAR(42) [NOT NULL]
  Indexes {
    ("code espèce", "nom", "date naissance", "num. enclos") [pk]
  }
}

Table "PEUT COHABITER AVEC" {
  "code espèce"            VARCHAR(42) [NOT NULL]
  "code espèce commensale" VARCHAR(42) [NOT NULL]
  "nb. max. commensaux"    VARCHAR(42)
  Indexes {
    ("code espèce", "code espèce commensale") [pk]
  }
}

Table "PEUT VIVRE DANS" {
  "code espèce"         VARCHAR(42) [NOT NULL]
  "num. enclos"         VARCHAR(42) [NOT NULL]
  "nb. max. congénères" VARCHAR(42)
  Indexes {
    ("code espèce", "num. enclos") [pk]
  }
}

Ref:"ANIMAL"."code espèce" > "ESPÈCE"."code espèce"
Ref:"ANIMAL".("code espèce mère", "date naissance mère", "nom mère") > "ANIMAL".("code espèce", "date naissance", "nom")
Ref:"OCCUPE".("code espèce", "date naissance", "nom") > "ANIMAL".("code espèce", "date naissance", "nom")
Ref:"PEUT COHABITER AVEC".("code espèce", "code espèce commensale") > "ESPÈCE".("code espèce", "code espèce")
Ref:"PEUT VIVRE DANS"."code espèce" > "ESPÈCE"."code espèce"
