Table "Entreprise" {
  "nom entreprise" VARCHAR(42) [pk, NOT NULL]
  "adresse"        VARCHAR(42)
  "téléphone"      VARCHAR(42)
}

Table "Étudiant" {
  "num étudiant"   VARCHAR(42) [pk, NOT NULL]
  "nom"            VARCHAR(42)
  "num. stage"     VARCHAR(42) [NOT NULL]
  "date signature" VARCHAR(42)
  "date"           VARCHAR(42) ["NULL"]
  "note stage"     VARCHAR(42)
  Indexes {
    "num. stage" [unique]
  }
}

Table "Stage" {
  "num. stage"       VARCHAR(42) [pk, NOT NULL]
  "sujet"            VARCHAR(42)
  "nom entreprise"   VARCHAR(42) [NOT NULL]
  "date proposition" VARCHAR(42)
}

Ref:"Étudiant"."num. stage" > "Stage"."num. stage"
Ref:"Stage"."nom entreprise" > "Entreprise"."nom entreprise"
