.open alt;

CREATE TABLE CLIENT (
  ref_client VARCHAR(8),
  nom VARCHAR(255),
  prenom VARCHAR(255),
  adresse VARCHAR(42),
  mail VARCHAR(255),
  PRIMARY KEY (ref_client)
);

CREATE TABLE FOO (
  foo VARCHAR(42),
  bar VARCHAR(42),
  biz VARCHAR(42),
  buz VARCHAR(42),
  qux VARCHAR(42),
  quux VARCHAR(42),
  PRIMARY KEY (foo)
);

CREATE TABLE UTILISER (
  carnet VARCHAR(42),
  projet VARCHAR(42),
  technicien VARCHAR(42),
  PRIMARY KEY (carnet, projet)
);

CREATE UNIQUE INDEX CLIENT_u1 ON CLIENT (nom, prenom);
CREATE UNIQUE INDEX CLIENT_u2 ON CLIENT (mail);
CREATE UNIQUE INDEX FOO_u1 ON FOO (bar, biz);
CREATE UNIQUE INDEX FOO_u2 ON FOO (biz, buz);
CREATE UNIQUE INDEX FOO_u3 ON FOO (qux, quux);
CREATE UNIQUE INDEX FOO_u1 ON FOO (quux, quux);
CREATE UNIQUE INDEX UTILISER_u1 ON UTILISER (carnet, technicien);
CREATE UNIQUE INDEX UTILISER_u2 ON UTILISER (projet, technicien);
