CREATE DATABASE IF NOT EXISTS triple_NNN;
USE triple_NNN;

CREATE TABLE APPLIQUER (
  employe VARCHAR(42),
  projet VARCHAR(42),
  competence VARCHAR(42),
  PRIMARY KEY (employe, projet, competence)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE COMPETENCE (
  competence VARCHAR(42),
  libelle VARCHAR(50),
  PRIMARY KEY (competence)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE EMPLOYE (
  employe VARCHAR(42),
  nom VARCHAR(255),
  PRIMARY KEY (employe)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE PROJET (
  projet VARCHAR(42),
  date_debut DATE,
  date_fin DATE,
  PRIMARY KEY (projet)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE APPLIQUER ADD FOREIGN KEY (competence) REFERENCES COMPETENCE (competence);
ALTER TABLE APPLIQUER ADD FOREIGN KEY (projet) REFERENCES PROJET (projet);
ALTER TABLE APPLIQUER ADD FOREIGN KEY (employe) REFERENCES EMPLOYE (employe);
