@startuml "cluster_NN1"

!define Table(x) class "x" << (T,#FFFFFF) >>
!define pk(x) <b>x</b>

Table("Voilier") {
    {field} + pk(num voilier)
    {field} + longueur
}

diamond N_ARY_0
N_ARY_0 -- "*" "Voilier"
N_ARY_0 -- "*" "Semaine"
N_ARY_0 -- "1" "Réservation"

Table("Semaine") {
    {field} + pk(num semaine)
    {field} + date début
}

Table("Réservation") {
    {field} + pk(num résa)
    {field} + arrhes
    {field} + date résa
    {field} + tarif
}

@enduml
