Table "Bataille" {
  "nom bataille" VARCHAR(42) [pk, NOT NULL]
  "lieu"         VARCHAR(42)
  "date"         VARCHAR(42)
}

Table "Trophée" {
  "numéro"         VARCHAR(42) [pk, NOT NULL]
  "type"           VARCHAR(42)
  "état"           VARCHAR(42)
  "nom villageois" VARCHAR(42) [NOT NULL]
  "nom bataille"   VARCHAR(42) [NOT NULL]
}

Table "Villageois" {
  "nom villageois" VARCHAR(42) [pk, NOT NULL]
  "adresse"        VARCHAR(42)
  "fonction"       VARCHAR(42)
}

Ref:"Trophée"."nom villageois" > "Villageois"."nom villageois"
Ref:"Trophée"."nom bataille" > "Bataille"."nom bataille"
