erDiagram
  CLIENT {
    TYPE Ref_client PK
    TYPE Nom
    TYPE Prenom
    TYPE Adresse
    TYPE Mail
  }
  FOO {
    TYPE foo PK
    TYPE bar
    TYPE biz
    TYPE buz
    TYPE qux
    TYPE quux
  }
  UTILISER {
    TYPE carnet PK
    TYPE projet PK
    TYPE technicien
  }