erDiagram
  CLIENT {
    TYPE ref_client PK
    TYPE nom
    TYPE prenom
    TYPE adresse
    TYPE mail
  }
  FOO {
    TYPE foo PK
    TYPE bar
    TYPE biz
    TYPE buz
    TYPE qux
    TYPE quux
  }
  UTILISER {
    TYPE carnet PK
    TYPE projet PK
    TYPE technicien
  }