@startuml "alt"

!define Table(x) class "x" << (T,#FFFFFF) >>
!define pk(x) <b>x</b>

Table("CLIENT") {
    {field} + pk(Réf. client)
    {field} + Nom
    {field} + Prénom
    {field} + Adresse
    {field} + Mail
}

Table("FOO") {
    {field} + pk(foo)
    {field} + bar
    {field} + biz
    {field} + buz
    {field} + qux
    {field} + quux
}

Table("UTILISER") {
    {field} + pk(carnet)
    {field} + pk(projet)
    {field} + technicien
}

@enduml
