erDiagram
  NEC {
    TYPE pulvinar PK
    TYPE audis
  }
  LACUS {
    TYPE tempor PK
    TYPE fugit
  }
  TRISTIS {
    TYPE magna PK
    TYPE vestibulum
  }
  SODALES {
    TYPE convallis PK
    TYPE ipsum
  }
  LACUS ||--|{ NEC: MOLLIS
  NEC }|--|| SODALES: VITAE
  SODALES }|--|{ LACUS: ULTRICES