erDiagram
  SUSCIPIT {
    TYPE orci PK
    TYPE lorem
  }
  SODALES {
    TYPE convallis PK
    TYPE ipsum
  }
  QUAM {
    TYPE cras PK
    TYPE sed
  }
  CONSEQUAT {
    TYPE fermentum PK
    TYPE dederit
  }
  TRISTIS {
    TYPE magna PK
    TYPE vestibulum
  }
  NEC {
    TYPE pulvinar PK
    TYPE audis
  }
  CURABITUR {
    TYPE gravida PK
    TYPE amor
  }
  DIGNISSIM {
    TYPE tellus PK
    TYPE terra
  }
  LACUS {
    TYPE tempor PK
    TYPE fugit
  }
  LIBERO {
    TYPE posuere PK
    TYPE lacrima
  }
  TRISTIS ||--|{ SUSCIPIT: RHONCUS
  QUAM }|--|| SODALES: VITAE
  TRISTIS }|--|| CONSEQUAT: ELIT
  CURABITUR ||--|{ NEC: MOLLIS
  TRISTIS }|--|{ DIGNISSIM: ALIQUET
  LIBERO }|--|{ LACUS: ULTRICES