@startuml "triple_111"

!define Table(x) class "x" << (T,#FFFFFF) >>
!define pk(x) <b>x</b>

Table("Technicien") {
    {field} + pk(technicien)
    {field} + nom technicien
}

diamond N_ARY_0
N_ARY_0 -- "1" "Technicien"
N_ARY_0 -- "1" "Carnet"
N_ARY_0 -- "1" "Projet"

Table("Projet") {
    {field} + pk(projet)
    {field} + libellé
}

Table("Carnet") {
    {field} + pk(carnet)
}

@enduml
