Table "Disponibilité" {
  "semaine" VARCHAR(42) [NOT NULL]
  "voilier" VARCHAR(42) [NOT NULL]
  Indexes {
    ("semaine", "voilier") [pk]
  }
}

Table "Réservation" {
  "id résa"          VARCHAR(42) [pk, NOT NULL]
  "num résa"         VARCHAR(42)
  "arrhes"           VARCHAR(42)
  "date réservation" VARCHAR(42)
  "semaine"          VARCHAR(42) [NOT NULL]
  "voilier"          VARCHAR(42) [NOT NULL]
  Indexes {
    "num résa" [unique]
    ("semaine", "voilier") [unique]
  }
}

Table "Semaine" {
  "semaine"    VARCHAR(42) [pk, NOT NULL]
  "date début" VARCHAR(42)
  Indexes {
    "date début" [unique]
  }
}

Ref:"Disponibilité"."semaine" > "Semaine"."semaine"
Ref:"Réservation".("semaine", "voilier") > "Disponibilité".("semaine", "voilier")
