from pathlib import Path
from json import dumps
from mocodo.convert.relations import set_defaults

debug_template = {
    "comment": f"Generated by 'create_debug_template.py'. Any change will be lost.",
    "stem_suffix": "_debug",
    "extension": "md",
    "to_defer": False,
    "highlight": "markdown",
    "column_separator": "",
    "compose_relation": "{columns}",
    "relation_separator": "",
    "transform_relation": [
        {
            "order": 100,
            "search": " None ",
            "replace": " ",
        }
    ],
    "compose_relational_schema": "| `this_relation_name` | `label` | `nature` | `adjacent_source` | `outer_source` |\n|:--|:--|:--|:--|:--|\n{relations}",
    "transform_relational_schema": [
        {
            "order": 100,
            "comment": "Abbreviate the consecutive relation names in the first column.",
            "search": '(?m)^((\\| [^"][^|]* \\|).+\n(\\2.+\n)*)\\2',
            "replace": '\\1| " |',
            "iterated": True,
        }
    ],
}
row = "| {this_relation_name} | {label} | `%s` | {adjacent_source} | {outer_source} |\n"

defaults = set_defaults({})
composition_keys = set(s for s in defaults.keys() if s.startswith("compose_"))
composition_keys.remove("compose_label_disambiguated_by_note")
composition_keys.remove("compose_label_disambiguated_by_number")
for key in sorted(composition_keys):
    debug_template.setdefault(f"{key}", row % key[len("compose_") :])
Path("mocodo/resources/relation_templates/debug.json").write_text(
    dumps(debug_template, indent=2, ensure_ascii=False)
)
