CREATE DATABASE IF NOT EXISTS cluster_NN1;
USE cluster_NN1;

CREATE TABLE RESERVATION (
  num_resa VARCHAR(8) NOT NULL,
  arrhes VARCHAR(42),
  date_resa DATE,
  num_voilier VARCHAR(8) NOT NULL,
  num_semaine VARCHAR(8) NOT NULL,
  tarif VARCHAR(42),
  PRIMARY KEY (num_resa)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE SEMAINE (
  num_semaine VARCHAR(8) NOT NULL,
  date_debut DATE,
  PRIMARY KEY (num_semaine)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE VOILIER (
  num_voilier VARCHAR(8) NOT NULL,
  longueur DECIMAL(10,2),
  PRIMARY KEY (num_voilier)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE RESERVATION ADD FOREIGN KEY (num_semaine) REFERENCES SEMAINE (num_semaine);
ALTER TABLE RESERVATION ADD FOREIGN KEY (num_voilier) REFERENCES VOILIER (num_voilier);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_u1 UNIQUE (num_voilier, num_semaine);
ALTER TABLE SEMAINE ADD CONSTRAINT SEMAINE_u1 UNIQUE (date_debut);
