Table "Réservation" {
  "num résa"    VARCHAR(42) [pk, not null]
  "arrhes"      VARCHAR(42)
  "date résa"   VARCHAR(42)
  "num voilier" VARCHAR(42) [not null]
  "num semaine" VARCHAR(42) [not null]
  "tarif"       VARCHAR(42)
  Indexes {
    ("num voilier", "num semaine") [unique]
  }
}

Table "Semaine" {
  "num semaine" VARCHAR(42) [pk, not null]
  "date début"  VARCHAR(42)
  Indexes {
    "date début" [unique]
  }
}

Table "Voilier" {
  "num voilier" VARCHAR(42) [pk, not null]
  "longueur"    VARCHAR(42)
}

Ref:"Réservation"."num voilier" > "Voilier"."num voilier"
Ref:"Réservation"."num semaine" > "Semaine"."num semaine"
