"Utiliser": { shape: sql_table
  "carnet":     VARCHAR(42) {constraint: [PK; UNQ1]}
  "projet":     VARCHAR(42) {constraint: [PK; UNQ2]}
  "technicien": VARCHAR(42) {constraint: [NOT NULL; UNQ1; UNQ2]}
}
