Table "Utiliser" {
  "carnet"     VARCHAR(42) [NOT NULL]
  "projet"     VARCHAR(42) [NOT NULL]
  "technicien" VARCHAR(42) [NOT NULL]
  Indexes {
    ("carnet", "projet") [pk]
    ("technicien", "projet") [unique]
    ("carnet", "technicien") [unique]
  }
}
