CREATE DATABASE IF NOT EXISTS triple_111;
USE triple_111;

CREATE TABLE UTILISER (
  carnet VARCHAR(42) NOT NULL,
  projet VARCHAR(42) NOT NULL,
  technicien VARCHAR(42) NOT NULL,
  PRIMARY KEY (carnet, projet)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE UTILISER ADD CONSTRAINT UTILISER_u1 UNIQUE (carnet, technicien);
ALTER TABLE UTILISER ADD CONSTRAINT UTILISER_u2 UNIQUE (projet, technicien);
