CREATE TABLE UTILISER (
  carnet VARCHAR(42),
  projet VARCHAR(42),
  technicien VARCHAR(42),
  PRIMARY KEY (carnet, projet)
);

ALTER TABLE UTILISER ADD CONSTRAINT UTILISER_u1 UNIQUE (carnet, technicien);
ALTER TABLE UTILISER ADD CONSTRAINT UTILISER_u2 UNIQUE (projet, technicien);
