CREATE DATABASE IF NOT EXISTS triple_NN1;
USE triple_NN1;

CREATE TABLE GERER (
  ingenieur VARCHAR(42),
  projet VARCHAR(42),
  responsable VARCHAR(42),
  PRIMARY KEY (ingenieur, projet)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
