CREATE DATABASE IF NOT EXISTS triple_NN1;
USE triple_NN1;

CREATE TABLE GERER (
  ingenieur VARCHAR(42) NOT NULL,
  projet VARCHAR(42) NOT NULL,
  responsable VARCHAR(42) NOT NULL,
  PRIMARY KEY (ingenieur, projet)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
