Table "Gérer" {
  "ingénieur"   VARCHAR(42) [NOT NULL]
  "projet"      VARCHAR(42) [NOT NULL]
  "responsable" VARCHAR(42) [NOT NULL]
  Indexes {
    ("ingénieur", "projet") [pk]
  }
}

Table "Ingénieur" {
  "ingénieur"     VARCHAR(42) [pk, NOT NULL]
  "nom ingénieur" VARCHAR(42)
}

Table "Projet" {
  "projet"         VARCHAR(42) [pk, NOT NULL]
  "libellé projet" VARCHAR(42)
}

Table "Responsable" {
  "responsable"     VARCHAR(42) [pk, NOT NULL]
  "nom responsable" VARCHAR(42)
}

Ref:"Gérer"."ingénieur" > "Ingénieur"."ingénieur"
Ref:"Gérer"."projet" > "Projet"."projet"
Ref:"Gérer"."responsable" > "Responsable"."responsable"
