Table "Affecter" {
  "projet"  VARCHAR(42) [NOT NULL]
  "employé" VARCHAR(42) [NOT NULL]
  "site"    VARCHAR(42) [NOT NULL]
  Indexes {
    ("projet", "employé") [pk]
    ("employé", "site") [unique]
  }
}
