CREATE DATABASE IF NOT EXISTS triple_N11;
USE triple_N11;

CREATE TABLE AFFECTER (
  projet VARCHAR(42) NOT NULL,
  employe VARCHAR(42) NOT NULL,
  site VARCHAR(42) NOT NULL,
  PRIMARY KEY (projet, employe)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE EMPLOYE (
  employe VARCHAR(42) NOT NULL,
  nom_employe VARCHAR(255),
  PRIMARY KEY (employe)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE PROJET (
  projet VARCHAR(42) NOT NULL,
  libelle VARCHAR(50),
  PRIMARY KEY (projet)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE SITE (
  site VARCHAR(42) NOT NULL,
  position POINT,
  PRIMARY KEY (site)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE AFFECTER ADD FOREIGN KEY (site) REFERENCES SITE (site);
ALTER TABLE AFFECTER ADD FOREIGN KEY (employe) REFERENCES EMPLOYE (employe);
ALTER TABLE AFFECTER ADD FOREIGN KEY (projet) REFERENCES PROJET (projet);
ALTER TABLE AFFECTER ADD CONSTRAINT AFFECTER_u1 UNIQUE (employe, site);
