Table "ALIQUET" {
  "magna"  VARCHAR(42) [NOT NULL]
  "tellus" VARCHAR(42) [NOT NULL]
  Indexes {
    ("magna", "tellus") [pk]
  }
}

Table "CONSEQUAT" {
  "fermentum" VARCHAR(42) [pk, NOT NULL]
  "dederit"   VARCHAR(42)
}

Table "CURABITUR" {
  "gravida" VARCHAR(42) [pk, NOT NULL]
  "amor"    VARCHAR(42)
}

Table "DIGNISSIM" {
  "tellus" VARCHAR(42) [pk, NOT NULL]
  "terra"  VARCHAR(42)
}

Table "LACUS" {
  "magna"  VARCHAR(42) [pk, NOT NULL]
  "tempor" VARCHAR(42)
  "fugit"  VARCHAR(42)
}

Table "LIBERO" {
  "posuere" VARCHAR(42) [pk, NOT NULL]
  "lacrima" VARCHAR(42)
}

Table "NEC" {
  "magna"    VARCHAR(42) [pk, NOT NULL]
  "pulvinar" VARCHAR(42)
  "audis"    VARCHAR(42)
  "gravida"  VARCHAR(42) [NOT NULL]
}

Table "QUAM" {
  "cras"  VARCHAR(42) [pk, NOT NULL]
  "sed"   VARCHAR(42)
  "magna" VARCHAR(42) [NOT NULL]
}

Table "SODALES" {
  "magna"     VARCHAR(42) [pk, NOT NULL]
  "convallis" VARCHAR(42)
  "ipsum"     VARCHAR(42)
}

Table "SUSCIPIT" {
  "orci"  VARCHAR(42) [pk, NOT NULL]
  "lorem" VARCHAR(42)
  "magna" VARCHAR(42) [NOT NULL]
}

Table "TRISTIS" {
  "magna"      VARCHAR(42) [pk, NOT NULL]
  "vestibulum" VARCHAR(42)
  "fermentum"  VARCHAR(42) [NOT NULL]
  "type"       UNSIGNED_INT [NOT NULL]
}

Table "ULTRICES" {
  "posuere" VARCHAR(42) [NOT NULL]
  "magna"   VARCHAR(42) [NOT NULL]
  Indexes {
    ("posuere", "magna") [pk]
  }
}

Ref:"ALIQUET"."magna" > "TRISTIS"."magna"
Ref:"ALIQUET"."tellus" > "DIGNISSIM"."tellus"
Ref:"LACUS"."magna" > "TRISTIS"."magna"
Ref:"NEC"."magna" > "TRISTIS"."magna"
Ref:"NEC"."gravida" > "CURABITUR"."gravida"
Ref:"QUAM"."magna" > "SODALES"."magna"
Ref:"SODALES"."magna" > "TRISTIS"."magna"
Ref:"SUSCIPIT"."magna" > "TRISTIS"."magna"
Ref:"TRISTIS"."fermentum" > "CONSEQUAT"."fermentum"
Ref:"ULTRICES"."posuere" > "LIBERO"."posuere"
Ref:"ULTRICES"."magna" > "LACUS"."magna"
