CREATE DATABASE IF NOT EXISTS inheritance;
USE inheritance;

CREATE TABLE ALIQUET (
  magna VARCHAR(42) NOT NULL,
  tellus VARCHAR(42) NOT NULL,
  PRIMARY KEY (magna, tellus)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE CONSEQUAT (
  fermentum VARCHAR(42) NOT NULL,
  dederit VARCHAR(42),
  PRIMARY KEY (fermentum)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE CURABITUR (
  gravida VARCHAR(42) NOT NULL,
  amor VARCHAR(42),
  PRIMARY KEY (gravida)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DIGNISSIM (
  tellus VARCHAR(42) NOT NULL,
  terra VARCHAR(42),
  PRIMARY KEY (tellus)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE LIBERO (
  posuere VARCHAR(42) NOT NULL,
  lacrima VARCHAR(42),
  PRIMARY KEY (posuere)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE QUAM (
  cras VARCHAR(42) NOT NULL,
  sed VARCHAR(42),
  magna VARCHAR(42) NOT NULL,
  PRIMARY KEY (cras)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE SUSCIPIT (
  orci VARCHAR(42) NOT NULL,
  lorem VARCHAR(42),
  magna VARCHAR(42) NOT NULL,
  PRIMARY KEY (orci)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE TRISTIS (
  magna VARCHAR(42) NOT NULL,
  vestibulum VARCHAR(42),
  fermentum VARCHAR(42) NOT NULL,
  type TINYINT UNSIGNED,
  convallis VARCHAR(42) NULL,
  ipsum VARCHAR(42) NULL,
  pulvinar VARCHAR(42) NULL,
  audis VARCHAR(42) NULL,
  gravida VARCHAR(42) NULL,
  tempor VARCHAR(42) NULL,
  fugit VARCHAR(42) NULL,
  PRIMARY KEY (magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE ULTRICES (
  posuere VARCHAR(42) NOT NULL,
  magna VARCHAR(42) NOT NULL,
  PRIMARY KEY (posuere, magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE ALIQUET ADD FOREIGN KEY (tellus) REFERENCES DIGNISSIM (tellus);
ALTER TABLE ALIQUET ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE QUAM ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE SUSCIPIT ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE TRISTIS ADD FOREIGN KEY (gravida) REFERENCES CURABITUR (gravida);
ALTER TABLE TRISTIS ADD FOREIGN KEY (fermentum) REFERENCES CONSEQUAT (fermentum);
ALTER TABLE ULTRICES ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE ULTRICES ADD FOREIGN KEY (posuere) REFERENCES LIBERO (posuere);
