Table "LACUS" {
  "magna"  VARCHAR(42) [pk, NOT NULL]
  "tempor" VARCHAR(42)
  "fugit"  VARCHAR(42)
}

Table "NEC" {
  "magna"            VARCHAR(42) [pk, NOT NULL]
  "pulvinar"         VARCHAR(42)
  "audis"            VARCHAR(42)
  "magna via_mollis" VARCHAR(42) [NOT NULL]
  "magna via_vitae"  VARCHAR(42) [NOT NULL]
}

Table "SODALES" {
  "magna"     VARCHAR(42) [pk, NOT NULL]
  "convallis" VARCHAR(42)
  "ipsum"     VARCHAR(42)
}

Table "TRISTIS" {
  "magna"      VARCHAR(42) [pk, NOT NULL]
  "vestibulum" VARCHAR(42)
  "type"       UNSIGNED_INT [NOT NULL]
}

Table "ULTRICES" {
  "magna sodales" VARCHAR(42) [NOT NULL]
  "magna lacus"   VARCHAR(42) [NOT NULL]
  Indexes {
    ("magna sodales", "magna lacus") [pk]
  }
}

Ref:"LACUS"."magna" > "TRISTIS"."magna"
Ref:"NEC"."magna" > "TRISTIS"."magna"
Ref:"NEC"."magna via_mollis" > "LACUS"."magna"
Ref:"NEC"."magna via_vitae" > "SODALES"."magna"
Ref:"SODALES"."magna" > "TRISTIS"."magna"
Ref:"ULTRICES"."magna sodales" > "SODALES"."magna"
Ref:"ULTRICES"."magna lacus" > "LACUS"."magna"
