CREATE DATABASE IF NOT EXISTS inheritance;
USE inheritance;

CREATE TABLE ALIQUET (
  magna VARCHAR(42),
  tellus VARCHAR(42),
  PRIMARY KEY (magna, tellus)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE CONSEQUAT (
  fermentum VARCHAR(42),
  dederit VARCHAR(42),
  PRIMARY KEY (fermentum)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE CURABITUR (
  gravida VARCHAR(42),
  amor VARCHAR(42),
  PRIMARY KEY (gravida)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DIGNISSIM (
  tellus VARCHAR(42),
  terra VARCHAR(42),
  PRIMARY KEY (tellus)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE LACUS (
  magna VARCHAR(42),
  tempor VARCHAR(42),
  fugit VARCHAR(42),
  PRIMARY KEY (magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE LIBERO (
  posuere VARCHAR(42),
  lacrima VARCHAR(42),
  PRIMARY KEY (posuere)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE NEC (
  magna VARCHAR(42),
  pulvinar VARCHAR(42),
  audis VARCHAR(42),
  gravida VARCHAR(42),
  PRIMARY KEY (magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE QUAM (
  cras VARCHAR(42),
  sed VARCHAR(42),
  magna VARCHAR(42),
  PRIMARY KEY (cras)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE SODALES (
  magna VARCHAR(42),
  convallis VARCHAR(42),
  ipsum VARCHAR(42),
  PRIMARY KEY (magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE SUSCIPIT (
  orci VARCHAR(42),
  lorem VARCHAR(42),
  magna VARCHAR(42),
  PRIMARY KEY (orci)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE TRISTIS (
  magna VARCHAR(42),
  vestibulum VARCHAR(42),
  fermentum VARCHAR(42),
  type TINYINT UNSIGNED,
  PRIMARY KEY (magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE ULTRICES (
  posuere VARCHAR(42),
  magna VARCHAR(42),
  PRIMARY KEY (posuere, magna)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE ALIQUET ADD FOREIGN KEY (tellus) REFERENCES DIGNISSIM (tellus);
ALTER TABLE ALIQUET ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE LACUS ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE NEC ADD FOREIGN KEY (gravida) REFERENCES CURABITUR (gravida);
ALTER TABLE NEC ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE QUAM ADD FOREIGN KEY (magna) REFERENCES SODALES (magna);
ALTER TABLE SODALES ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE SUSCIPIT ADD FOREIGN KEY (magna) REFERENCES TRISTIS (magna);
ALTER TABLE TRISTIS ADD FOREIGN KEY (fermentum) REFERENCES CONSEQUAT (fermentum);
ALTER TABLE ULTRICES ADD FOREIGN KEY (magna) REFERENCES LACUS (magna);
ALTER TABLE ULTRICES ADD FOREIGN KEY (posuere) REFERENCES LIBERO (posuere);
