Table "Appartement" {
  "code rue"     VARCHAR(42) [NOT NULL]
  "num immeuble" VARCHAR(42) [NOT NULL]
  "num étage"    VARCHAR(42) [NOT NULL]
  "num appart."  VARCHAR(42) [NOT NULL]
  "nb pièces"    VARCHAR(42)
  Indexes {
    ("code rue", "num immeuble", "num étage", "num appart.") [pk]
  }
}

Table "Étage" {
  "code rue"        VARCHAR(42) [NOT NULL]
  "num immeuble"    VARCHAR(42) [NOT NULL]
  "num étage"       VARCHAR(42) [NOT NULL]
  "nb appartements" VARCHAR(42)
  Indexes {
    ("code rue", "num immeuble", "num étage") [pk]
  }
}

Table "Immeuble" {
  "code rue"     VARCHAR(42) [NOT NULL]
  "num immeuble" VARCHAR(42) [NOT NULL]
  "nb étages"    VARCHAR(42)
  Indexes {
    ("code rue", "num immeuble") [pk]
  }
}

Table "Rue" {
  "code rue" VARCHAR(42) [pk, NOT NULL]
  "nom rue"  VARCHAR(42)
}

Ref:"Appartement".("code rue", "num étage", "num immeuble") > "Étage".("code rue", "num étage", "num immeuble")
Ref:"Étage".("code rue", "num immeuble") > "Immeuble".("code rue", "num immeuble")
Ref:"Immeuble"."code rue" > "Rue"."code rue"
