Table "Exemplaire" {
  "œuvre"      VARCHAR(42) [NOT NULL]
  "exemplaire" VARCHAR(42) [NOT NULL]
  "nb pages"   VARCHAR(42)
  "date achat" VARCHAR(42)
  "foobar"     VARCHAR(42)
  Indexes {
    ("œuvre", "exemplaire") [pk]
  }
}

Table "Œuvre" {
  "œuvre"  VARCHAR(42) [pk, NOT NULL]
  "auteur" VARCHAR(42)
}

Ref:"Exemplaire"."œuvre" > "Œuvre"."œuvre"
