CREATE TABLE COMMANDE (
  PRIMARY KEY (commande),
  commande VARCHAR(42) NOT NULL,
  date     DATE
);

CREATE TABLE LIGNE_DE_COMMANDE (
  PRIMARY KEY (commande, produit),
  commande VARCHAR(42) NOT NULL,
  produit  VARCHAR(42) NOT NULL,
  quantite INTEGER
);

CREATE TABLE PRODUIT (
  PRIMARY KEY (produit),
  produit VARCHAR(42) NOT NULL,
  libelle VARCHAR(50)
);

ALTER TABLE LIGNE_DE_COMMANDE ADD FOREIGN KEY (produit) REFERENCES PRODUIT (produit);
ALTER TABLE LIGNE_DE_COMMANDE ADD FOREIGN KEY (commande) REFERENCES COMMANDE (commande);
