Table "Commande" {
  "commande" VARCHAR(42) [pk, NOT NULL]
  "date"     VARCHAR(42)
}

Table "Ligne de commande" {
  "commande" VARCHAR(42) [NOT NULL]
  "produit"  VARCHAR(42) [NOT NULL]
  "quantité" VARCHAR(42)
  Indexes {
    ("commande", "produit") [pk]
  }
}

Table "Produit" {
  "produit" VARCHAR(42) [pk, NOT NULL]
  "libellé" VARCHAR(42)
}

Ref:"Ligne de commande"."commande" > "Commande"."commande"
Ref:"Ligne de commande"."produit" > "Produit"."produit"
