@startuml "triple_NN1"

!define Table(x) class "x" << (T,#FFFFFF) >>
!define pk(x) <b>x</b>

Table("Ingénieur") {
    {field} + pk(ingénieur)
}

diamond N_ARY_0
N_ARY_0 -- "1" "Responsable"
N_ARY_0 -- "1..*" "Ingénieur"
N_ARY_0 -- "1..*" "Projet"

Table("Projet") {
    {field} + pk(projet)
}

Table("Responsable") {
    {field} + pk(responsable)
}

@enduml
