Table "AYANT-DROIT" {
  "matricule"       VARCHAR(42) [NOT NULL]
  "nom ayant-droit" VARCHAR(42) [NOT NULL]
  "lien"            VARCHAR(42)
  Indexes {
    ("matricule", "nom ayant-droit") [pk]
  }
}

Table "COMPOSER" {
  "réf. pièce composée"   VARCHAR(42) [NOT NULL]
  "réf. pièce composante" VARCHAR(42) [NOT NULL]
  "quantité"              VARCHAR(42)
  Indexes {
    ("réf. pièce composée", "réf. pièce composante") [pk]
  }
}

Table "DÉPARTEMENT" {
  "num. département" VARCHAR(42) [pk, NOT NULL]
  "nom département"  VARCHAR(42)
}

Table "EMPLOYÉ" {
  "matricule"        VARCHAR(42) [pk, NOT NULL]
  "nom employé"      VARCHAR(42)
  "num. département" VARCHAR(42) [NOT NULL]
}

Table "FOURNIR" {
  "num. projet"  VARCHAR(42) [NOT NULL]
  "réf. pièce"   VARCHAR(42) [NOT NULL]
  "num. société" VARCHAR(42) [NOT NULL]
  "qté fournie"  VARCHAR(42)
  Indexes {
    ("num. projet", "réf. pièce", "num. société") [pk]
  }
}

Table "PIÈCE" {
  "réf. pièce"    VARCHAR(42) [pk, NOT NULL]
  "libellé pièce" VARCHAR(42)
}

Table "PROJET" {
  "num. projet"           VARCHAR(42) [pk, NOT NULL]
  "nom projet"            VARCHAR(42)
  "matricule responsable" VARCHAR(42) ["NULL"]
}

Table "REQUÉRIR" {
  "num. projet" VARCHAR(42) [NOT NULL]
  "réf. pièce"  VARCHAR(42) [NOT NULL]
  "qté requise" VARCHAR(42)
  Indexes {
    ("num. projet", "réf. pièce") [pk]
  }
}

Table "SOCIÉTÉ" {
  "num. société"      VARCHAR(42) [pk, NOT NULL]
  "raison sociale"    VARCHAR(42)
  "num. société mère" VARCHAR(42) ["NULL"]
}

Table "TRAVAILLER" {
  "matricule"   VARCHAR(42) [NOT NULL]
  "num. projet" VARCHAR(42) [NOT NULL]
  Indexes {
    ("matricule", "num. projet") [pk]
  }
}

Ref:"AYANT-DROIT"."matricule" > "EMPLOYÉ"."matricule"
Ref:"COMPOSER".("réf. pièce composée", "réf. pièce composante") > "PIÈCE".("réf. pièce", "réf. pièce")
Ref:"EMPLOYÉ"."num. département" > "DÉPARTEMENT"."num. département"
Ref:"FOURNIR"."num. projet" > "PROJET"."num. projet"
Ref:"FOURNIR"."réf. pièce" > "PIÈCE"."réf. pièce"
Ref:"FOURNIR"."num. société" > "SOCIÉTÉ"."num. société"
Ref:"PROJET"."matricule responsable" > "EMPLOYÉ"."matricule"
Ref:"REQUÉRIR"."num. projet" > "PROJET"."num. projet"
Ref:"REQUÉRIR"."réf. pièce" > "PIÈCE"."réf. pièce"
Ref:"SOCIÉTÉ"."num. société mère" > "SOCIÉTÉ"."num. société"
Ref:"TRAVAILLER"."matricule" > "EMPLOYÉ"."matricule"
Ref:"TRAVAILLER"."num. projet" > "PROJET"."num. projet"
