CREATE DATABASE IF NOT EXISTS basic;
USE basic;

CREATE TABLE CLIENT (
  ref_client VARCHAR(8) NOT NULL,
  nom VARCHAR(255),
  prenom VARCHAR(255),
  adresse VARCHAR(42),
  PRIMARY KEY (ref_client)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE COMMANDE (
  num_commande VARCHAR(8) NOT NULL,
  date DATE,
  montant DECIMAL(10,2),
  PRIMARY KEY (num_commande)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE INCLURE (
  num_commande VARCHAR(8) NOT NULL,
  ref_produit VARCHAR(8) NOT NULL,
  quantite INTEGER,
  PRIMARY KEY (num_commande, ref_produit)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE PASSER (
  ref_client VARCHAR(8) NOT NULL,
  num_commande VARCHAR(8) NOT NULL,
  PRIMARY KEY (ref_client, num_commande)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE PRODUIT (
  ref_produit VARCHAR(8) NOT NULL,
  libelle VARCHAR(50),
  prix_unitaire DECIMAL(10,2),
  PRIMARY KEY (ref_produit)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE INCLURE ADD FOREIGN KEY (ref_produit) REFERENCES PRODUIT (ref_produit);
ALTER TABLE INCLURE ADD FOREIGN KEY (num_commande) REFERENCES COMMANDE (num_commande);
ALTER TABLE PASSER ADD FOREIGN KEY (num_commande) REFERENCES COMMANDE (num_commande);
ALTER TABLE PASSER ADD FOREIGN KEY (ref_client) REFERENCES CLIENT (ref_client);
