Table "CLIENT" {
  "Réf. client" VARCHAR(42) [pk, NOT NULL]
  "Nom"         VARCHAR(42)
  "Prénom"      VARCHAR(42)
  "Adresse"     VARCHAR(42)
}

Table "COMMANDE" {
  "Num. commande" VARCHAR(42) [pk, NOT NULL]
  "Date"          VARCHAR(42)
  "Montant"       VARCHAR(42)
  "Réf. client"   VARCHAR(42) [NOT NULL]
}

Table "INCLURE" {
  "Num. commande" VARCHAR(42) [NOT NULL]
  "Réf. produit"  VARCHAR(42) [NOT NULL]
  "Quantité"      VARCHAR(42)
  Indexes {
    ("Num. commande", "Réf. produit") [pk]
  }
}

Table "PRODUIT" {
  "Réf. produit"  VARCHAR(42) [pk, NOT NULL]
  "Libellé"       VARCHAR(42)
  "Prix unitaire" VARCHAR(42)
}

Ref:"COMMANDE"."Réf. client" > "CLIENT"."Réf. client"
Ref:"INCLURE"."Num. commande" > "COMMANDE"."Num. commande"
Ref:"INCLURE"."Réf. produit" > "PRODUIT"."Réf. produit"
