CREATE DATABASE IF NOT EXISTS reflexive;
USE reflexive;

CREATE TABLE COMPOSER (
  piece_composante VARCHAR(42) NOT NULL,
  piece_composee VARCHAR(42) NOT NULL,
  PRIMARY KEY (piece_composante, piece_composee)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE HOMME (
  num_ss VARCHAR(8) NOT NULL,
  nom VARCHAR(255),
  prenom VARCHAR(255),
  num_ss_pere VARCHAR(8) NULL,
  PRIMARY KEY (num_ss)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE HOMME ADD FOREIGN KEY (num_ss_pere) REFERENCES HOMME (num_ss);
