Table COMPOSER {
  "pièce" VARCHAR(42) [not null]
  "pièce 1" VARCHAR(42) [not null]
  Indexes {
    ("pièce", "pièce 1") [pk]
  }
}

Table HOMME {
  "Num. SS" VARCHAR(42) [pk, not null]
  Nom VARCHAR(42)
  "Prénom" VARCHAR(42)
  "Num. SS 1" VARCHAR(42) [not null]
}

Ref:HOMME."Num. SS 1" > HOMME."Num. SS"
