CREATE TABLE AGENCE (
  PRIMARY KEY (id_agence),
  id_agence  VARCHAR(8) NOT NULL,
  nom_agence VARCHAR(255)
);

CREATE TABLE DIRECTION_REGIONALE (
  PRIMARY KEY (id_dir),
  id_dir  VARCHAR(8) NOT NULL,
  nom_dir VARCHAR(255)
);

CREATE TABLE SUPERVISER (
  PRIMARY KEY (id_agence),
  id_agence VARCHAR(8) NOT NULL,
  id_dir    VARCHAR(8) NOT NULL
);

ALTER TABLE SUPERVISER ADD FOREIGN KEY (id_dir) REFERENCES DIRECTION_REGIONALE (id_dir);
ALTER TABLE SUPERVISER ADD FOREIGN KEY (id_agence) REFERENCES AGENCE (id_agence);
