CREATE DATABASE IF NOT EXISTS protected;
USE protected;

CREATE TABLE EROS (
  congue VARCHAR(42) NOT NULL,
  PRIMARY KEY (congue)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE LACUS (
  blandit VARCHAR(42) NOT NULL,
  elit VARCHAR(42),
  PRIMARY KEY (blandit)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE LIGULA (
  blandit VARCHAR(42) NOT NULL,
  congue VARCHAR(42) NOT NULL,
  metus VARCHAR(42),
  PRIMARY KEY (blandit)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE LIGULA ADD FOREIGN KEY (congue) REFERENCES EROS (congue);
ALTER TABLE LIGULA ADD FOREIGN KEY (blandit) REFERENCES LACUS (blandit);
